### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by Raynos** [petermichaux/uMVC#1]
Show an example explaining why the glue (controller.setModel, controller.setView, sub views) etc are useful.

It's not obvouis why the implementation can't be boiled down to Models that are observers and views that just observe a single model and update themself.

Nor is it obvouis what part of the code implements the strategy and composite patterns (I presume the composite pattern is the sub views?)

**Comment by petermichaux** [comment]
Yes more examples and docs would be good. See the gang of four and Head First Design Patterns for the basics.

Yes the subview are part of the composite pattern.

**Comment by Raynos** [comment]
I understand the design patterns. I do not understand how the code is an implemtation of them.

This is particularly relevant as your recent blog posts taunts me with 

>  something every JavaScript programmer should understand inside out 

basically implying I'm no good because your code is ungrokable by me.

**Comment by petermichaux** [comment]
A model is observable and views can observe it. This is the observer pattern.

A view can have subviews. This is the composite pattern.

A view has a changeable controller and delegates decision making to the controller. This is the strategy pattern.

These three patterns together comprise the MVC architecture.

**Comment by Raynos** [comment]
@petermichaux the third is simply saying that the view has side effects and some arbitrary thing (the controller) handles those side effects.

How is that "the strategy pattern"

**Comment by petermichaux** [comment]
A controller implements a strategy to make decisions about what those side effects are. Changing the controller changes the strategy and hence changes the side effects. That is the strategy pattern.

**Comment by Raynos** [comment]
@petermichaux  A function implements logic to make decisions ... Changing a function changes the logic.

Does that mean that all higher order functions are strategy patterns?

**Comment by petermichaux** [comment]
No. A controller alone is not the strategy pattern. A function alone is not the strategy pattern. The strategy pattern is about the fact that the view has property that stores a controller and that the view's controller can be changed to change the view's behavior.

**Comment by Raynos** [comment]
Can you give an example of when a view instance would dynamically change it's controller at run time. 

Would a text editor view changing from display state to edit state be implemented as swapping the display controller for the edit controller on the view?

Would changing the filtering logic of a list be implemented as changing the filtering controller on the list view component?

**Comment by petermichaux** [comment]
The classic example is a button that does something when one controller is used and is disabled and does nothing when another controller is used.

Keyboard controls of a text editor could be implemented as the strategy pattern. When one controller is in use, typing the 'j' character actually inserts a 'j' character into the text of the document. When another controller is in use, typing the 'j' character could move the cursor down to the next line.

Not sure about the filtering example.

**Comment by Raynos** [comment]
Some kind of summary of this conversation would surely benefit others as well.

**Comment by yckart** [comment]
:+1: Push!
